sonar.projectKey=oakleylin_taiwan-select-theme
sonar.organization=oakleylin
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.min.js,**/*.min.css,**/images/**,.github/**
sonar.sourceEncoding=UTF-8
