sonar.projectKey=oakleylin_Taiwanselect_e026057a-4d5e-49cf-9094-3f972076798a
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.min.js,**/*.min.css,**/images/**,.github/**
sonar.coverage.exclusions=**/*
sonar.sourceEncoding=UTF-8
